import { z } from 'zod';
import {
  SourceType,
  AssetType,
  LifecycleStatus,
  ProcessingStatus,
  ChecksumAlgorithm,
} from './types';

export const SourceTypeSchema = z.nativeEnum(SourceType);
export const AssetTypeSchema = z.nativeEnum(AssetType);
export const LifecycleStatusSchema = z.nativeEnum(LifecycleStatus);
export const ProcessingStatusSchema = z.nativeEnum(ProcessingStatus);
export const ChecksumAlgorithmSchema = z.nativeEnum(ChecksumAlgorithm);

export const CloudAssetRecordSchema = z.object({
  id: z.string().min(1),
  workspaceId: z.string().optional(),
  campaignId: z.string().optional(),
  executionId: z.string().optional(),
  executionTaskId: z.string().optional(),
  providerJobId: z.string().optional(),
  creativeLibraryAssetId: z.string().optional(),
  parentAssetId: z.string().optional(),
  sourceType: SourceTypeSchema,
  assetType: AssetTypeSchema,
  lifecycleStatus: LifecycleStatusSchema,
  processingStatus: ProcessingStatusSchema,
  originalFilename: z.string().optional(),
  displayName: z.string(),
  mimeType: z.string().optional(),
  extension: z.string().optional(),
  byteSize: z.number().int().nonnegative().optional(),
  width: z.number().int().positive().optional(),
  height: z.number().int().positive().optional(),
  durationSeconds: z.number().nonnegative().optional(),
  checksum: z.string().optional(),
  checksumAlgorithm: ChecksumAlgorithmSchema.optional(),
  storageProvider: z.string().optional(),
  storageKey: z.string().optional(),
  bucket: z.string().optional(),
  region: z.string().optional(),
  publicUrl: z.string().url().or(z.string().length(0)).or(z.string().startsWith('/')).optional(),
  signedUrl: z.string().url().or(z.string().length(0)).optional(),
  signedUrlExpiresAt: z.string().datetime().or(z.string()).optional(),
  thumbnailUrl: z.string().url().or(z.string().length(0)).or(z.string().startsWith('/')).optional(),
  previewUrl: z.string().url().or(z.string().length(0)).or(z.string().startsWith('/')).optional(),
  metadata: z.record(z.unknown()).optional(),
  tags: z.array(z.string()),
  modelProvider: z.string().optional(),
  modelName: z.string().optional(),
  promptHistoryId: z.string().optional(),
  digitalHumanId: z.string().optional(),
  productId: z.string().optional(),
  wardrobeItemId: z.string().optional(),
  sceneId: z.string().optional(),
  retentionPolicy: z.string().optional(),
  retentionUntil: z.string().datetime().or(z.string()).optional(),
  legalHold: z.boolean().optional(),
  deletionRequestedAt: z.string().datetime().or(z.string()).optional(),
  deletedAt: z.string().datetime().or(z.string()).optional(),
  createdAt: z.string().datetime().or(z.string()),
  updatedAt: z.string().datetime().or(z.string()),
  uploadedAt: z.string().datetime().or(z.string()).optional(),
  processedAt: z.string().datetime().or(z.string()).optional(),
  archivedAt: z.string().datetime().or(z.string()).optional(),
  failureCode: z.string().optional(),
  failureMessage: z.string().optional(),
  attemptCount: z.number().int().nonnegative(),
});
