import { z } from 'zod';
import {
  PUBLISHING_ADAPTER_MODES,
  PUBLISHING_CONNECTION_STATUSES,
  PUBLISHING_JOB_STATUSES,
  PUBLISHING_PLATFORMS,
  PUBLICATION_STATUSES,
} from '../types';

const validationIssueSchema = z.object({
  code: z.string().min(1),
  field: z.string().min(1),
  message: z.string().min(1),
  severity: z.enum(['error', 'warning']),
});

export const publicationValidationSchema = z.object({
  valid: z.boolean(),
  issues: z.array(validationIssueSchema),
  checkedAt: z.string().datetime(),
  policyVersion: z.string().min(1),
});

export const publicationDraftSchema = z.object({
  id: z.string().min(1),
  workspaceId: z.string().min(1),
  campaignId: z.string().optional(),
  workflowId: z.string().optional(),
  creativePlanId: z.string().optional(),
  executionRunId: z.string().optional(),
  executionTaskId: z.string().optional(),
  creativeAssetId: z.string().optional(),
  cloudAssetId: z.string().optional(),
  digitalHumanId: z.string().optional(),
  productId: z.string().optional(),
  experimentId: z.string().optional(),
  variantId: z.string().optional(),
  metadata: z.record(z.any()).optional(),
  platform: z.enum(PUBLISHING_PLATFORMS),
  connectionId: z.string().optional(),
  title: z.string(),
  caption: z.string(),
  hashtags: z.array(z.string()),
  mentions: z.array(z.string()),
  destinationUrl: z.string().url().optional(),
  thumbnailAssetId: z.string().optional(),
  status: z.enum(PUBLICATION_STATUSES),
  approvalRequired: z.boolean(),
  approvedAt: z.string().datetime().optional(),
  approvedBy: z.string().optional(),
  rejectedAt: z.string().datetime().optional(),
  rejectionReason: z.string().optional(),
  scheduledAt: z.string().datetime().optional(),
  timezone: z.string().min(1),
  adapterMode: z.enum(PUBLISHING_ADAPTER_MODES),
  validation: publicationValidationSchema,
  idempotencyKey: z.string().min(1),
  activeJobId: z.string().optional(),
  remotePostId: z.string().optional(),
  permalink: z.string().url().optional(),
  publishedAt: z.string().datetime().optional(),
  failureCode: z.string().optional(),
  failureMessage: z.string().optional(),
  attemptCount: z.number().int().min(0),
  metricsStatus: z.enum(['not-requested', 'waiting', 'collecting', 'complete', 'failed']),
  archivedAt: z.string().datetime().optional(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

export const publishingJobSchema = z.object({
  id: z.string().min(1),
  publicationId: z.string().min(1),
  platform: z.enum(PUBLISHING_PLATFORMS),
  adapterMode: z.enum(PUBLISHING_ADAPTER_MODES),
  status: z.enum(PUBLISHING_JOB_STATUSES),
  idempotencyKey: z.string().min(1),
  attempt: z.number().int().min(1),
  maxAttempts: z.number().int().min(1),
  scheduledAt: z.string().datetime().optional(),
  startedAt: z.string().datetime().optional(),
  completedAt: z.string().datetime().optional(),
  remotePostId: z.string().optional(),
  permalink: z.string().url().optional(),
  failureCode: z.string().optional(),
  failureMessage: z.string().optional(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

export const publishingConnectionSchema = z.object({
  id: z.string().min(1),
  platform: z.enum(PUBLISHING_PLATFORMS),
  displayName: z.string().min(1),
  accountLabel: z.string(),
  status: z.enum(PUBLISHING_CONNECTION_STATUSES),
  adapterMode: z.enum(PUBLISHING_ADAPTER_MODES),
  enabled: z.boolean(),
  lastVerifiedAt: z.string().datetime().optional(),
  updatedAt: z.string().datetime(),
});
