export const ROUTES = {
  root: '/',
  aiDirector: '/ai-director',
  dashboard: '/dashboard',
  research: '/research',
  viralAnalyzer: '/viral-analyzer',
  campaignBuilder: '/campaign-builder',
  executionCenter: '/execution-center',
  providerGateway: '/provider-gateway',
  assetPipeline: '/asset-pipeline',
  publishingHub: '/publishing-hub',
  campaigns: '/campaigns',
  digitalHumans: '/digital-humans',
  characters: '/characters',
  products: '/products',
  wardrobe: '/wardrobe',
  scenes: '/scenes',
  poses: '/poses',
  promptIntelligence: '/prompt-intelligence',
  promptEngine: '/prompt-engine',
  creativeLibrary: '/creative-library',
  analytics: '/analytics',
  experimentation: '/experimentation',
  settings: '/settings',
  creativeRecipes: '/creative-recipes',
  analyticsFeedbackLoop: '/analytics-feedback-loop',
};
